### PR TITLE
Fix autovacuum renamed autoVacuum

### PR DESCRIPTION
**Pull request by fngx**
Solves #68

### CODE REVIEW

**Comment by fngx** [comment]
- [ ] ```git tag -a v0.1.1```

**Comment by fngx** [comment]
Great, I right now mainly use dav. But git should be a nice addition next.
Carefully keeping an eye on this part, along with few others.

**Comment by mickael-kerjean** [comment]
[Here it is](https://github.com/mickael-kerjean/nuage/commit/0677d2f03f383e3b2f6c691ae67bb68c1cff1056).

Should be much better now. FYI the autovacuum is there as GIT is the only connector that requires downloading the entire repo in the filesystem to do anything. dav is much faster

**Comment by fngx** [comment]
Wow, then that's fantastic; pretty sure git back-end is going to solve other use cases I had, regarding caching. Ready checking that.
Thanks.

**Pull request merged**
