### PR TITLE
Add packages for docker to build successfully

### PR DESCRIPTION
**Pull request by fngx**

### CODE REVIEW

**Comment by mickael-kerjean** [comment]
Thanks, I'm merging but that will be update very soon as I'm working on statically compiling everything so that no dependencies will be needed at all

**Comment by fngx** [comment]
Thanks, guess it's time for me to read all the (valuable) roadmap steps religiously.

Also, I'm not too familiar with go static resources embedding right now, so I might have to continue using docker for building (webpack?) or deploying purposes.

**Comment by mickael-kerjean** [comment]
Go statis resources is one thing, the real struggle is embedding C lib within the package ... That's a huge pain in the butt

**Comment by fngx** [comment]
Sure, all I see right now are docker multi-arch or else.. oldschool gcc compile flags

**Pull request merged**
